/* user TABLE */
CREATE TABLE users(id VARCHAR(100) NOT NULL PRIMARY KEY, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, score_get INT(10) NOT NULL, score_bool BOOLEAN NOT NULL DEFAULT FALSE) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

/* problem TABLE */
CREATE TABLE problem(num  INT(10) NOT NULL PRIMARY KEY, title CHAR(255) NOT NULL, content TEXT(65535) NOT NULL, answer TEXT(65535) NOT NULL, testcase TEXT(65535) NOT NULL, answer_input TEXT(65535) NOT NULL) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;